name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: naresh0406/podcast-generator@main

